version: "3"

services:

  web:

    # replace :mywebapp with your name and image details

    image: devrajaem/class1:app1

    deploy:

      replicas: 3

      resources:

        limits:

          cpus: "0.2"

          memory: 100M

      restart_policy:

        condition: on-failure

    ports:

      - "8082:80"

    networks:

      - webnet

networks:

 webnet:
